version: "3.2"
services:
  pictshare:
    build: .
    ports:
      - "8999:80"
    volumes:
      - ./data:/usr/share/nginx/html/data
    environment:
      URL: 'http://localhost:8999/'
      MAX_UPLOAD_SIZE: 1024
      ALLOWED_SUBNET: '172.22.0.0/24'
